directory: /home/sam/External/Music
library: /home/sam/.local/share/beets/musiclibrary.db

import:
  move: yes
  write: yes
  log: /home/sam/.local/share/beets/import.log

plugins: bandcamp check chroma duplicates export fromfilename fuzzy importadded info missing play random web

paths:
  # For random collections of music received from people that don't have a specific order
  collection::^.+$: $collection/$artist - $title
  
  default: $albumartist - $album [$original_year]/$track $title
  singleton: $artist/$title
  comp: $album [$original_year]/$track $title
  

include:
  - config-follow-muspy.yaml

extrafiles:
  patterns:
    all: '*.*'

play:
  command: /usr/bin/rhythmbox
