templates:
  podcast:
    accept_all: yes
    limit_new: 1
    download:
      path: /home/sam/Podcasts/
      # FIXME: we hardcode the .mp3 extension, which works by coincidence.
      # FlexGet doesn't seem to support renaming while keeping the extension
      # of the original file.
      # (See also: https://discuss.flexget.com/t/how-to-rename-the-files-and-keep-the-file-extension-at-download/3684
      #  which is wrong).
      filename: '{{title}}.mp3'

tasks:
  #living-adventurously:
  #  rss: https://feeds.transistor.fm/living-adventurously
  #  template: podcast
  no-such-thing-as-a-fish:
    rss: https://audioboom.com/channels/2399216.rss
    template: podcast
  adam-buxton:
    rss: http://rss.acast.com/adambuxton
    template: podcast
  new-york-times:
    rss: http://rss.art19.com/the-daily
    template: podcast
  song-exploder:
    rss: http://feed.songexploder.net/SongExploder
    template: podcast
    limit_new: 2
  scroobius-pip:
    rss: http://rss.acast.com/distractionpieces
    template: podcast
  lost-map:
    rss: https://www.lostmap.com/podcast?format=rss
    template: podcast
  rob-auton-podcast:
    rss: https://rss.acast.com/robautonpodcast
    template: podcast
  blindboy:
    rss: https://rss.acast.com/blindboy
    template: podcast
  chris-demakes-a-podcast:
    rss: https://feeds.megaphone.fm/JJW5546407535
    template: podcast
    limit_new: 2
